trailingComma = "es5"
tabWidth = 2
semi = true
singleQuote = true
jsxBracketSameLine = true
plugins = ["@trivago/prettier-plugin-sort-imports"]
importOrder = ["^src/lib/(.*)$", "^src/components/(.*)$", "^src/views/(.*)$", "^src/assets/(.*)$", "^src/(.*)", "^[./]"]
importOrderSeparation = true
importOrderSortSpecifiers = true
