name: Scheduled Publish

on:
  schedule:
    - cron: "0 20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Echo
        run: |
          echo "Starting at: $(date)"
